# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 964c99d797f5710df176715d3c5f8c63686e879523b08b41ff1b969d0a52d8f5444e61f9f64dca60cbe3241a1e11b237ac97fcf3d992048aae0ff1920f8fafc0

test:
  secret_key_base: 25d1f1ad3d6b96ec4e3814d8a195cb75bff24ec76586fa13b069d88064ed68fe96f0bd0096e9f683211c4c31e5dfea30eaf72ac82b22de6b8ac74148e8409da1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
